# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.nixosModules.hostVortigaunt =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      # fileSystems."/" = {
      #   device = "/dev/disk/by-uuid/e510e423-a51d-4afd-b8b6-0945e370f228";
      #   fsType = "ext4";
      # };
      #
      # fileSystems."/boot" = {
      #   device = "/dev/disk/by-uuid/4DF2-42DC";
      #   fsType = "vfat";
      #   options = [
      #     "fmask=0077"
      #     "dmask=0077"
      #   ];
      # };
      #
      # swapDevices = [
      #   { device = "/dev/disk/by-uuid/0e6454b6-7d82-42e4-99cc-28ee98469ce6"; }
      # ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
